Fix nullable char* being passed to std::string
std::string should only be assigned non-null values (string, c-string,
char). As ifa_name field is specifically a Nullable char*, the null part
causes the warning. We make sure ifa_name is not equal to nullptr, we
can get rid of the warning by casting it to char* _Nonnull and using
this variable.

system/netd/server/InterfaceControllerTest.cpp:207:54: error: implicit
conversion from nullable pointer 'char * _Nullable' to non-nullable
pointer type 'const char * _Nonnull'
[-Werror,-Wnullable-to-nonnull-conversion]
  207 |         const auto ifacePair =
ifaceMap.value().find(ifa->ifa_name);

Bug: 430598176
Test: m with new compiler && presubmit
Change-Id: I7e9e48d8c2a25ed9f56b66e5ca189d7108e17e32