Fix nullable string being passed to std::string
std::string should only be assigned non-null values (string, c-string,
char). As addr->ifa_name is a char*, it can be null causing this warning
so it can be fixed if we just check it is a nullptr before it gets
passed to std::string.

system/netd/tests/binder_test.cpp:1168:25: error: implicit conversion
from nullable pointer 'char * _Nullable' to non-nullable pointer type
'const char * _Nonnull' [-Werror,-Wnullable-to-nonnull-conversion]
 1168 |         if (std::string(addr->ifa_name) != ifname ||
      |                         ^
system/netd/tests/binder_test.cpp:1168:25: error: implicit conversion
from nullable pointer 'char * _Nullable' to non-nullable pointer type
'const char * _Nonnull' [-Werror,-Wnullable-to-nonnull-conversion]

Bug: 430598176
Test: m && presubmit
Change-Id: I67348d7234548e311f9e0bf5d087e2cc615a1c77